### ISSUE TITLE
FunctionDeclaration

### ISSUE THREAD

**Issue by makkingtosh** [ShivamSarodia/ShivyC#103] opened 2018-05-27 23:56 UTC
hello_world.c  tokenizer.py
$ shivyc hello_world.c
hello_world.c:2:5: error: function definition missing parameter name
  int main(void){
      ----------

**Comment by ShivamSarodia** [comment] 2018-09-03 02:04
Thanks for the report! Duplicate of https://github.com/ShivamSarodia/ShivyC/issues/81 so closing.

**Closed by ShivamSarodia** 2018-09-03 02:04 UTC
